### ISSUE TITLE
Improve Readability of the Website by Improving Contrast and Fonts

### ISSUE THREAD

**Issue by justinefication** [codeigniter4projects/website#385]
Unlike the previous version of CodeIgniter's website, the current website does not provide enough contrast to improve readability. Also, the choice of font or font weight needs to be improved as well.

As seen in the following screenshot, the thinness of the font weight does not provide enough contrast and makes it hard for the text to be read.

![CI-Website-Screenshot](https://github.com/codeigniter4projects/website/assets/40228037/ad99891e-b9c7-4af3-bdf9-e3657838e1a7)

Raleway's Extra Light is literally extra light, I suggest you refrain from using it, rather use either Light or Regular. Better yet, choose a different font.

**Comment by demyr17** [comment]
This version of the website has been live for the past few years and this is the first complaint we have received about the font&colors etc.

Upon your comment now, I have just visited the page trying it in several browsers (Firefox, Chrome, Edge and Opera) but I haven't seen such a color scheme that you see and also the font-weight is not so thin, even though we have it in our list in the css file. Because we also have **normal** and **bold** **font-weight**s there (font-weight: 400 and 700). Also the colors of the texts are not grey. We use **#252525** and **#111111** for dark colors which are fair, I believe. 

Thus, to investigate further, may I kindly ask which browser you are using or even the OS that you're using? Is our website the first website you have had such a problem with? 

Thanks

**Comment by justinefication** [comment]
Hi @demyr17 I'm using Google Chrome version 114.0.5735.134 to view the website. Also, I'm using Windows 11 22H2 wiht build number 22621.1848. Hope this helps.

It's been a while since I used PHP and CodeIgniter, the last version of CodeIgniter I used was 3 during which CodeIgniter 4 was in alpha stage.

**Comment by kenjis** [comment]
macOS 12.6.6
Google Chrome 114.0.5735.133

![Screenshot 2023-06-25 11 34 11](https://github.com/codeigniter4projects/website/assets/87955/2bb35aae-bc5f-4707-8ab9-93621171e0c3)

**Comment by justinefication** [comment]
Hi @kenjis 

Unfortunately, we're not seeing the same overall appearance.

**Comment by datamweb** [comment]
**Chrome**
Version 114.0.5735.134 (Official Build) (64-bit)

![Screenshot 2023-06-27 202930](https://github.com/codeigniter4projects/website/assets/9530214/1703c250-1b06-46fc-b6dd-b8a83eda0a57)

**Firefox**
Version  114.0.2 (32-bit)

![firefox](https://github.com/codeigniter4projects/website/assets/9530214/4931450a-61c1-490b-8ea4-a4ba7f2f6548)

**Edge**
Version 114.0.1823.58 (Official build) (64-bit)

![eg](https://github.com/codeigniter4projects/website/assets/9530214/bdcc0b7c-d361-4fb2-a126-06581242b097)

**Comment by kenjis** [comment]
@justinefication I am not sure why the text is so thin in your environment.

**Comment by justinefication** [comment]
@kenjis so do I. Tried clearing browser cache and cookies as well as clearing my font cache. But to no avail. Tried the website on the following browsers:

**Microsoft Edge**
Version 114.0.1823.58 (Official build) (64-bit)

**Google Chrome**
Version 114.0.5735.198 (Official Build) (64-bit)

**Firefox**
Version 114.0.2 (64-bit)

Both Chromium-based browser rendered the page as reported. However, Firefox renders it just fine. Anyhow, thanks for the help.

**Comment by MGatner** [comment]
Thanks for the report and ensuing investigation! It sounds like this is probably an environment or OS settings issue. Safe to close?

**Comment by demyr17** [comment]
Hi @MGatner , It's nice to see you here again.

@justinefication , When I check our css file I see that we have _Raleway ExtraLight - font-weight: 200_ in our font list but we don't use it anywhere. We have _font-weight:600_ that are used in following lines even though we don't have _font-weight: 600_ in our list. We have _font-weight:700_. So, I will fix it. But I guess it will not solve your problem because in the end, the default weight we use for body is 400.

**Comment by justinefication** [comment]
Hi @MGatner sorry for responding late. Thank you for taking the time to look into the issue. Yes it is safe to close this.

**Comment by justinefication** [comment]
@demyr17 that's cool. I'll still look into it in my environment when I have the opportunity. Thank you so much.
